### ISSUE TITLE
malloc.h on OS X

### ISSUE THREAD

**Issue by ralphschindler** [derickr/quickhash#6]
malloc.h on os.x is located at ```/usr/include/malloc/malloc.h```, which makes compilation of lib/quickhash.c fail, is there a way to make this machine dependent?

**Comment by derickr** [comment]
Can you try https://github.com/derickr/quickhash/tree/header-fixes and see if that branch compiles for you? It is possible that some of the mmap code is going to be Linux specific though, and I don't have a Mac to test against.

**Comment by ralphschindler** [comment]
:+1: That compiles and runs for me.
